name:                palindrome-checker
version:             0.1.0.0
github:              "sergfa/palindrome-checker"
license:             BSD3
author:              "Sergey Fayman"
maintainer:          "sergfa@gmail.com"
copyright:           "2018 Sergey Fayman"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/sergfa/palindrome-checker#readme>

dependencies:
- base >= 4.7 && < 5
- text

library:
  source-dirs: src
  
executables:
  palindrome-checker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - palindrome-checker
    - text

tests:
  palindrome-checker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - palindrome-checker
    - text
